### ISSUE TITLE
Deployment Error

### ISSUE THREAD

**Issue by progrmoiz** [frandiox/hydrogen-vercel-edge#1]
Thank you for the project. I tried deploying the project to vercel, I did added the environment variable but in the very end getting unexpected error. 

![image](https://user-images.githubusercontent.com/33980210/159850168-f8d0f701-cc5f-4893-8bba-64dea8f6f202.png)

**Comment by sebDaDev** [comment]
Hi, I was able to get it working on vercel, but I can't update hydrogen for some reason

**Comment by frandiox** [comment]
This was related to some changes in Vercel itself. This repo now uses the latest APIs from Vercel to deploy so this shouldn't be an issue anymore. Also, there's now official support for Hydrogen: https://vercel.com/changelog/hydrogen-projects-can-now-be-deployed-with-zero-configuration
